Traceback (most recent call last):
  File "C:\Users\shinki\Anaconda3\lib\site-packages\nbclient\client.py", line 622, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "C:\Users\shinki\Anaconda3\lib\site-packages\nbclient\util.py", line 85, in ensure_async
    result = await obj
  File "C:\Users\shinki\Anaconda3\lib\site-packages\jupyter_client\asynchronous\channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shinki\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\shinki\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\shinki\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\shinki\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\shinki\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\shinki\Anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\shinki\Anaconda3\lib\site-packages\nbclient\client.py", line 841, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "C:\Users\shinki\Anaconda3\lib\site-packages\nbclient\client.py", line 646, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "C:\Users\shinki\Anaconda3\lib\site-packages\nbclient\client.py", line 696, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['return_all = pd.DataFrame()', '', "for code in kosdaq_list['code']:  ", '    ', "    stock_return = merged[merged['code']==code].sort_index()"]
...
["    c2 = (stock_return['return'] > 1) # 수익율 1 보다 큼. 당일 종가가 전일 종가보다 큼 (개별 종목)", "    stock_return['win_market'] = np.where((c1&c2), 1, 0) # C1 과 C2 조건을 동시에 만족하면 1, 아니면 0", '    return_all = pd.concat([return_all, stock_return], axis=0) ', '    ', "return_all.to_pickle('return_all.pkl')"]
-------------------

